### PR TITLE
Python 3 and Marshmallow 3

### PR DESCRIPTION
**Pull request by TMiguelT**
* Use Marshmallow 3, and fix code and tests that is tied to Marshmallow 2
* Since we're using Marshmallow 3, and since Python 2 is about to hit EOL, remove it from the Travis tests
* Streamline installation by removing `requirements.txt` and adding additional dev packages to the dev extras
* Add helpful assertion messages to the assert statements in the tests
* Add some more recent versions of Python to Travis

### CODE REVIEW

**Comment by joeblackwaslike** [comment]
This is really nice, good work here. I wish a maintainer would merge it already because that's the only thing keeping me from using this library for a geospatial-temporal data api.

If I had to guess why it hasn't been merged already, I would say it was because the pull request addresses multiple concerns and the maintainer may not want to address all of those at once.  If you broke it up into seperate PR's it would be easier to review.  One for marshmallow 3 support, another for removing python 2 from tests, etc...

**Comment by TMiguelT** [comment]
> If I had to guess why it hasn't been merged already, I would say it was because the pull request addresses multiple concerns and the maintainer may not want to address all of those at once, especially dropping python2 tests

This *might* be an issue for merging, but the main problem is that the maintainers have just disappeared. They haven't commenting or committed  anything for months.  I tried to email them but got no response. What I'm going to do, though, is publish my fork on PyPi so people can use it (I also need it for another project).

**Comment by TMiguelT** [comment]
Also I think Marshmallow 3 is only compatible with Python 3 anyway, which is why I did this in one big PR.

**Comment by Donnyvdm** [comment]
> What I'm going to do, though, is publish my fork on PyPi so people can use it (I also need it for another project).

I'd be interested in this. Will your fork be just for this issue or do you plan to maintain your fork more actively? If so, I'd happily switch over as well (and submit PRs there). Please let me know where I can find it once it's out.

**Comment by TMiguelT** [comment]
> I'd be interested in this. Will your fork be just for this issue or do you plan to maintain your fork more actively? If so, I'd happily switch over as well (and submit PRs there). Please let me know where I can find it once it's out.

Head over to https://github.com/TMiguelT/flapison. I've already made 8 releases on PyPi since forking it (changelog [here](https://github.com/TMiguelT/flapison/blob/master/CHANGELOG.md)).

I am planning on maintaining this generally, so I'm open to issues and PRs. In addition, I'm considering incompatibilities with `flask-rest-jsonapi` to be bugs (at least until I do a new major version), so let me know if you encounter any.

**Pull request merged**
