### PR TITLE
Auto-deploy to pypi on release tag

### PR DESCRIPTION
**Pull request by kumy**
Added the necessary template to `.travis.yml` file to auto-deploy on pypi and create/push the release to GitHub releases.

@akira-dev Don't forget to adapt the `secure` fields to include your encrypted password or tokens. You may use `travis` cli for such task. I personnaly use it in a docker container `docker run -it --rm -v $PWD:/repo -v ~/.travis:/travis ubergarm/travis-ci-cli envrypt` from inside your git clone.

The doc regarding such conf: https://docs.travis-ci.com/user/deployment/releases#authenticating-with-an-oauth-token

### CODE REVIEW

**Comment by akira-dev** [comment]
Ok thanks I will take a look of that

**Comment by akira-dev** [comment]
Do you use this library in production ?

**Comment by kumy** [comment]
Our project is not yet production ready, but yes we use it as the base for the rewrite of geokrety.org. You may find us on GitHub. Thanks for this awsome library!!

**Comment by akira-dev** [comment]
Thanks but after thinking about that I have a too chaotic developement workflow so I don't want to publish a new release on pypi each time a push on the master branch

**Comment by kumy** [comment]
As you wish, but it was configured to deploy on new tag only ;)

**Pull request closed without merging**
